services:
  weather-app:
    image: valet128/weather
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./weather:/weather

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
